name: Pinas XML Feed Merge

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (00:00, 12:00 UTC)
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  merge-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run merge script
        run: python pinas_merge.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pinas_merged_feed.xml
          git commit -m "Update Pinas merged XML feed $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/arjay81/pinas.git
